# Generated by Django 6.0.4 on 2026-08-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='condition',
            field=models.CharField(default='Like new', max_length=100),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='location',
            field=models.CharField(default='On campus', max_length=100),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='price_suffix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='seller_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='seller_sales_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='category',
            field=models.CharField(choices=[('textbooks', 'Textbooks'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('services', 'Services')], max_length=50),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
