# Generated by Django 6.1.1 on 2026-10-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_marketplacelisting_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/marketplace/'),
        ),
    ]
