# Generated by Django 6.1.1 on 2026-10-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_marketplacelisting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='quantity_available',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity available'),
        ),
    ]
