# Generated by Django 6.0.4 on 2026-08-17 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('TEXTBOOKS', 'Textbooks'), ('NOTES', 'Lecture Notes'), ('PAST_PAPERS', 'Past Papers'), ('OTHER', 'Other')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pdf_file', models.FileField(upload_to='uploads/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
