# Generated by Django 6.0.4 on 2026-08-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='price',
        ),
    ]
