# Generated by Django 6.1.1 on 2026-10-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0002_remove_resource_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/course_material/'),
        ),
    ]
